import React from "react";

const Home = () => {
  return (
    <div className="main-page-content">
      <div id="home">
        <div id="particles-js"></div>
        <div className="home-content-main">
          <div className="table-cell">
            <div className="container">
              <div className="row home-row">
                <div className="col-md-12 col-sm-12">
                  <div className="home-text wow fadeIn text-center">
                    <h1 className="cd-headline clip is-full-width">
                      <span
                        className="cd-words-wrapper"
                        style={{ width: "266px", overflow: "hidden" }}
                      >
                        <b className="is-hidden">ArtiScan</b>
                        <b className="is-hidden">Group 4</b>
                        <b className="is-visible">Major Project</b>
                      </span>
                    </h1>
                    <div className="about-social-icon text-center">
                      <ul className="about-social">
                        <li className="wow fadeIn" data-wow-delay=".4s">
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="parallax" data-velocity="-.1"></div>
        <div className="parallax" data-velocity="-.5" data-fit="525"></div>
      </div>

      {/* <!-- ================================ ABOUT =============================== --> */}

      <div id="about">
        <div className="about-content">
          <div className="love-grid text-center">
            <div className="container">
              <div className="row">
                <div className="col-md-12">
                  <div className="main-title text-center wow fadeIn">
                    <h3>ABOUT</h3>
                    <div className="underline1"></div>
                    <div className="underline2"></div>
                    <p>
                      Artiscan is a tool generated by using Ml and AI. This tool
                      provide a complete platform for recognizing artifacts and
                      3d recontruction of the artifacts. Right now there is no
                      such tool present in the market which can both recognize
                      and 3d recontruct the artifacts. Please feel free to use
                      our website and provide various inputs to our model. You
                      review will be appriciated.
                    </p>
                  </div>
                </div>
              </div>
              <div className="row love-row wow fadeIn">
                <div className="col-md-3 col-sm-6">
                  <div className="love-details" data-wow-delay=".1s">
                    <i
                      className="fa fa-pencil-square-o love-icon"
                      aria-hidden="true"
                    ></i>
                    <h3>Tools Used</h3>
                    <div className="underline1"></div>
                    <div className="underline2"></div>
                    <p>Python, React, HTML, CSS, JavaScript</p>
                  </div>
                </div>
                <div className="col-md-3 col-sm-6">
                  <div className="love-details" data-wow-delay=".3s">
                    <i
                      className="fa fa-file-image-o love-icon"
                      aria-hidden="true"
                    ></i>
                    <h3>Algorithms</h3>
                    <div className="underline1"></div>
                    <div className="underline2"></div>
                    <p>Random forest , greedy </p>
                  </div>
                </div>
                <div className="col-md-3 col-sm-6">
                  
                </div>
                <div className="col-md-3 col-sm-6">
                  
                </div>
              </div>
            </div>
          </div>

          <div className="about-back"></div>
          <div className="me-grid">
            <div className="container">
              <div className="row">
                <div className="col-md-4 col-sm-6 col-xs-12 about-col">
                  <div className="about-image">
                    <img
                      // image here solution ke sath
                      src="https://2.bp.blogspot.com/_X3On-WPzL1w/S-icAFjTAmI/AAAAAAAAAMY/0y93eh42Z2k/s1600/25group.jpg"
                      alt="coins"
                      className="about-img wow fadeIn"
                    />
                  </div>
                </div>
                <div className="col-md-8 col-sm-6 col-xs-12 about-col">
                  <div className="about-details wow fadeIn">
                    <div className="main-title left-title text-left wow fadeIn">
                      <h3>Solution</h3>
                      <div className="underline1 no-margin"></div>
                      <div className="underline2 no-margin"></div>
                    </div>
                    <p className="wow fadeIn">
                      To develop a high-performing image classification model
                      capable of diffrentiating coin artifacts from varius other
                      artifacts. Thr model would exhibit a remarkable level of
                      accuracy, ensuring that it correctly identifies the
                      presence or absence of coin artifacts in the a given
                      dataset.{" "}
                      <a className="underline2" href="#contact">
                        {" "}
                        here.
                      </a>{" "}
                      Build a deep convolutional neural network (CNN) model for
                      coins to predict the era in which they were minted.
                      <br />
                      <br />
                      Develop an engaging user interface that allows individuals
                      to upload images and obtain immediate outcomes and offers
                      visual representations of artifacts.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="work-counter text-center">
            <div className="counter">
              <div className="container">
                <div className="row wow fadeIn">
                  <div className="col-md-3 col-sm-6">
                    <div className="work-statistics">
                      <img
                        // image here solution ke sath
                        src="https://m.media-amazon.com/images/I/91ARNedth9L.jpg"
                        alt="coins"
                        className="about-img wow fadeIn"
                      />
                      <h3 className="Count">Coins</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                    </div>
                  </div>
                  <div className="col-md-3 col-sm-6">
                    <div className="work-statistics">
                      <img
                        // image here solution ke sath
                        src="https://i.pinimg.com/474x/cb/8b/81/cb8b81c824cb5a0c46e3f3e3b31836f5.jpg"
                        alt="coins"
                        className="about-img wow fadeIn"
                      />
                      <h3 className="Count">Pots</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                    </div>
                  </div>
                  <div className="col-md-3 col-sm-6">
                    <div className="work-statistics">
                      <img
                        // image here solution ke sath
                        src="https://www.worldhistory.org/uploads/images/10064.jpg"
                        alt="coins"
                        className="about-img wow fadeIn"
                      />
                      <h3 className="Count">Vessels</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                    </div>
                  </div>
                  <div className="col-md-3 col-sm-6">
                    <div className="work-statistics">
                      <img
                        // image here solution ke sath
                        src="https://d.newsweek.com/en/full/2325157/ancient-bronze-belt-buckles.jpg"
                        alt="buckle"
                        className="about-img wow fadeIn"
                      />
                      <h3 className="Count">Buckle</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* <!-- ================================ History =============================== --> */}

      <div id="history">
        <div className="history-main">
          <div className="container">
            <div className="row">
              <div className="col-md-12">
                <div className="main-title text-center wow fadeIn">
                  <h3>History</h3>
                  <div className="underline1"></div>
                  <div className="underline2"></div>
                  <p>
                    An artifact is a general term for an item made or given
                    shape by humans, such as a tool or a work of art, especially
                    an object of archaeological interest. In archaeology, the
                    word has become a term of particular nuance and is defined
                    as an object recovered by archaeological endeavor, which may
                    be a cultural artifact having cultural interest.
                  </p>
                </div>
              </div>
            </div>
            <div className="row love-row wow fadeIn">
              <div className="col-md-6">
                <div className="skill-details text-left">
                  <p>
                    Artifact is the general term used in archaeology, while in
                    museums the equivalent general term is normally "object",
                    and in art history perhaps artwork or a more specific term
                    such as "carving". The same item may be called all or any of
                    these in different contexts, and more specific terms will be
                    used when talking about individual objects, or groups of
                    similar ones. Artifacts exist in many different forms and
                    can sometimes be confused with ecofacts and features; all
                    three of these can sometimes be found together at
                    archaeological sites. They can also exist in different types
                    of context depending on the processes that have acted on
                    them over time. A wide variety of analyses take place to
                    analyze artifacts and provide information on them. However,
                    the process of analyzing artifacts through scientific
                    archaeology can be hindered by the looting and collecting of
                    artifacts, which sparks ethical debate.
                  </p>

                  {/* <img
                        // image here solution ke sath
                        src="https://d.newsweek.com/en/full/2325157/ancient-bronze-belt-buckles.jpg"
                        alt="buckle"
                        className="major"
                      /> */}
                </div>
              </div>
              <div className="col-md-6">
                <img
                  // image here solution ke sath
                  src="https://giffywalls-images.imgix.net/catalog/product/d/t/dtil60-woodcut-vase-design-wallpaper-murals.jpg?w=271&h=271&fit=crop&blend-w=271&blend-h=271&blend-fit=scale&blend-mode=multiply&mark-w=271&mark-h=271&mark-fit=scale&mark-pad=0&mark=https://giffywalls-images.imgix.net/giffywalls/murals/mockups/6/8/a/0/a01.png&blend=https://giffywalls-images.imgix.net/giffywalls/murals/mockups/6/8/a/0/a01.jpg&dpr=2&auto=format,compress&upscale=true"
                  alt="buckle"
                  className="major"
                />
                <div className="skill-details">
                  <div className="content">
                    <div className="col">
                      <ul id="skill-main"></ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* <!-- ================================ Time period =============================== --> */}

      <div id="time-period">
        <div className="timeperiod-content">
          <div className="timeperiod-grid text-center">
            <div className="container">
              <div className="row">
                <div className="col-md-12">
                  <div className="main-title text-center wow fadeIn">
                    <h3>Time period</h3>
                    <div className="underline1"></div>
                    <div className="underline2"></div>
                    <p>
                      In our model various time period of articats are covered
                    </p>
                  </div>
                </div>
              </div>
              <div className="row love-row wow fadeIn">
                <div className="col-md-4 col-sm-4">
                  <div className="resume-details" data-wow-delay=".2s">
                    <div className="resume-hover"></div>
                    <div className="resume-main">
                      {/* <i
                          className="fa fa-home resume-icon"
                          aria-hidden="true"
                        ></i> */}
                      <img
                        // image here solution ke sath
                        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTNLu_Xfg_M_GaUkxDuKBqKEzR3IfV1Il1wIDZijYF9uw5gI1LpzA4iYLVvZFb2"
                        alt="coins"
                        className="about-img wow fadeIn"
                      />
                      <h3>Stone Age</h3>
                      <h2>2.6 million years ago to about 10,000 years ago</h2>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        This is the earliest period of human history, and it is
                        characterized by the use of stone tools. The Stone Age
                        is typically divided into three subperiods: the
                        Paleolithic, Mesolithic, and Neolithic. The Paleolithic
                        period lasted from about 2.6 million years ago to about
                        10,000 years ago. The Mesolithic period lasted from
                        about 10,000 years ago to about 8,000 years ago. The
                        Neolithic period lasted from about 8,000 years ago to
                        about 3,000 years ago.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 col-sm-4">
                  <div className="resume-details" data-wow-delay=".3s">
                    <div className="resume-hover"></div>
                    <div className="resume-main">
                      <img
                        // image here solution ke sath
                        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTb1ov489BkPcAyjut64uVlOjLeMNVzRDH2vW5SICYecmDOuK2EgP8PaIkCnX6d"
                        alt="coins"
                        className="about-img wow fadeIn"
                      />
                      <h3>Bronze Age</h3>
                      <h2>3,000 years ago to about 1,200 years</h2>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        The Bronze Age, following the Stone Age, marked a
                        significant advancement in human civilization with the
                        widespread use of bronze for tools, weapons, and
                        artifacts. It emerged around 3300 BCE and lasted until
                        roughly 1200 BCE. Characterized by the smelting of
                        copper and tin to create bronze, this era witnessed the
                        rise of complex societies, metallurgy, and significant
                        cultural developments across various regions.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 col-sm-4">
                  <div className="resume-details" data-wow-delay=".4s">
                    <div className="resume-hover"></div>
                    <div className="resume-main">
                      <img
                        // image here solution ke sath
                        src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQMLeCzmlHWbTRutmrKFDh-2sPFQWSIp0Xu1ekl4x26oZeph7AyiVeEM_2kQueT"
                        alt="coins"
                        className="about-img wow fadeIn"
                      />
                      <h3>Medieval</h3>
                      <h2>500 AD to about 1500 AD</h2>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        The Medieval Period, also known as the Middle Ages,
                        spanned roughly from the 5th to the 15th century AD in
                        Europe. It was characterized by feudalism, the dominance
                        of the Catholic Church, and significant cultural,
                        political, and economic changes. This era saw the rise
                        and fall of kingdoms, the Crusades, the emergence of
                        universities, and the flowering of art and architecture,
                        including the Gothic style.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* <!-- ================================ Demo pics of artifacts =============================== --> */}

      <div id="work">
        <div className="work-content">
          <div className="work-grid">
            <div className="container">
              <div className="row">
                <div className="col-md-12">
                  <div className="main-title text-center wow fadeIn">
                    <h3>Demo Artifact Images</h3>
                    <div className="underline1"></div>
                    <div className="underline2"></div>
                    <p>
                      Here are a few artifact images taken from{" "}
                      <a
                        className="underline2"
                        href="https://finds.org.uk/"
                        target="_blank"
                      >
                        here.
                      </a>
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="container">
              <div className="gallery" style={{ paddingTop: "80px" }}>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/isabelledigglekent/medium/KENT-4DB68C_65d4db91f1bb3.jpg"
                      alt="Coin iron age"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/mforeman/medium/NLM-4CB406_65d4cccfa34f2.jpg"
                      alt="Object type: VESSEL
                      Broad period: MEDIEVAL"
                    />
                  </div>
                </a>
                <div className="gallery-item">
                  <img
                    className="gallery-image"
                    src="https://finds.org.uk/images/meggard1/medium/LEIC-768403_65d76a3330d72.jpg"
                    alt="Object type: BUCKLE
                    Broad period: POST MEDIEVAL"
                  />
                </div>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/tgilmore/medium/WMID-757A66_65d7582c95916.jpg"
                      alt="Object type: COIN
                      Broad period: ROMAN"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/thumbnails/x1264207.jpg.pagespeed.ic.Z8Ka2-K9DL.webp"
                      alt="Object type: COIN
                      Broad period: ROMAN"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/thumbnails/x1264199.jpg.pagespeed.ic.K9o_xz2cuP.webp"
                      alt="Object type: COIN
                      Broad period: ROMAN"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/kadams/medium/GLO-743715_65d7437c1ab2f.jpg"
                      alt="Object type: CORE
                      Broad period: MESOLITHIC"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://finds.org.uk/images/thumbnails/x1264192.jpg.pagespeed.ic.AKddNCNBxY.webp"
                      alt="Object type: COIN
                      Broad period: ROMAN"
                    />
                  </div>
                </a>
                <a href="#">
                  {/* <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="data:image/webp;base64,UklGRmQJAABXRUJQVlA4IFgJAADwKQCdASpzAGQAPmkuk0WkIqIVugcYQAaEsoBq2HbJETLvc7Qnpj/5HpX+n/0q86N6M961kBnF3zs/A/bTksRHe4f9b+YHtL30y3EAXzeeGnqa+F/NN9FP914nX3H/X+wH/Jv6//2f8L+R31F/5n/s88aar+zKS072pSyfUafmidJ31SX1p/N6kaGOS6tP2UPULbkxLgY1lvU5xphE5xDjhT4OCk/cKcLVS8zLdZh7Zb8/s6j2+IB91TPIxWLFlMhhJChoyzkv9SVsBEj8lZsFEwxcX0Ud/xoGY6m5w21Yp19JdN+yOz3AxG+vEqi5MxHBEMi/WOTVGgBWQvHM2DVHAiTVp33nuIijV1m3Ak9jD39D1tCyiC2bRX/c+ZjYYkWZf8oyx5HIrHtUcfdt36+8sVFJxCN6jOR+B63u3/tBQGlln9HtllLq+Mhyw3Muv75zi9HNoI2WgAD+/v9y06dwunm5ZptrCVheNBz23VskTfn4KfZy1j4p3c2Dz/fV094Ka3VW/766z4XvZsurt7X6iSKq+MXrnLAx/StS98hAuhK7+DnaIkOZdJBId/sglIB9Mqx28lInu/Pof9CbTUwK8GwfVnF4qU5bvVOG0G2rfXvNCutE1VnJIVvJVopzWXI74BwT6c+y166Ni7mPDq4W8WJXHNFGQqiCvBB0wRi2yTxBmLIeOuocl56EPspOcJ8KR8m2lTMNYvQvs3882U8kXQ/p23QFXMYAjBiGEioh+1VeaFhhyRVqEa6mW7jQuAPZlLf8+kvElfN7A0+ElRetJ/Bi0ft7r2tPfdtZPrD5H45Tx8+Mh4w0RLpyL2dKLMNMJ6TkFaeg78IeWi1ltcIaZOKGGM392rIxBUfuIbzVSZ5EaivxQ8wnG6J4YHnh28FXfuofJ10CE9WdCBYR2l0CXQWr6iXzUPPLd3poT8ALXC+Q3DP9Z721D5C/QtcLmz27MaAqpdY0m3lD18JRGkI1wcEQltprJDlU5WNMwA/FMV7ZyR34BTgAY8CljtDAmn9AQUaxiXnYc2NyUZcGewwfzjMqm1lIJnT8BbhA3+VvHvbIqE7rXWMJXHSgy97/cHcOD+9E1m7TnUqmwG4902ONtTOGntSQx6FOMx22lLuAW6Gs2J9WRgxszY6F0ZZZbrUvOGvzde05UzuHGO6ZNm+7qgQ9kPIv/lSeswhTDIlXtKsUWQcEJWtX/AYbtcr5Uawu6J1VXiNBaixY+aSkzCJ3TVXsf4BRorOJrS9xpLxwZoshXqCGkz0mWxNfV6P3Tu8przpCra4g1C3Nkx0BJC5yJFmsH17wWTCikytzXRBCJw2T1bOeGKZUNNLorB8DRPKfyDm6RVdkHWoLYfVnByzosMBZySsREm6gcnZkqpA2RoZ9dG2aumki8zvAVVokLFl8tbwe/OveYVKSd0TPatQOwlKVIX2GAOn1uJBf4Qq2xshCUG4Z+aeHMErawg3DhhgtYVp+8eoezt4LyPQl2ewileM34avDdN61/kR0PEt29AudaZ74gVAhO1CRsjZbqAj9KAWAGqmZwpVfkemVpvNiUFuEV0fkfml2WNimx46v2LW61beK3H9a2LMcs/zraKxgTHIpj4cM8CGXYblFvSx9asBGMFK7O58NUvYQc//MykRuQ+8M+M22kr+Ey99J/lXR0/QX6amlfxhrr28RyI2oWIL1Ny2gKIM/fkkc1k2tv77kcpQkoHeIgRPa5Ko9+bgbCG1HRaSLzGtoTkFmAx7J+GG9yNU/ygb4gtdliBXgxVh80R+5A7VEP1O0iUGObjQrLXgH4BnYGWQhZZ3syW9aOZB0rZXINdntzmdKIj8KU9KM6mr/pFCT/cZQoSgLqgHCvGbqe6F+EgtwaQkFQasRpbySYRjtYSod9Bpks/GLBBxtLZf9e+z4vQ44vdbibmXTQuJdIemzXh5BE0ejC6kReDNTlEqsLwNx6MFgJPbl/EgEyyyijMBgyUht6dGDG/vzrGImdwbMjRhHaOileJegkv5f3bB2DEWhrw4enRnJTLeA6OM7YyaoxRjXzTIKnNE+/M9ZRMY0uvqmaLoUxWef824H75F/D96DB2sPt4bNUL6xY3dU/CeVI66wyyJyVeP237S+qfCsFvWLi/14oO9URfzIw8mZv56df35ixqkUDpu+YOiSE06HfYn0GEPN5m49MJ+l+9frWnUBd78AAzNUIInmLYgw9CAkRA5eMRqutdIc7kBQUpz+XdyvzHY01yE1Dqw9hmeD+RgJKAUjiiLSudeWNehTeZxDETAl1XfWnA6uOPUmcrlTue1U8escDTpOmSEocy2dpOkwOVpW7WffBhhSeT17s/tqp5jTZAllzD5FCcRK3uOJCdbBhNie0bdr55oq48987djz7/p8vY4+fjxZi+KZ2lZ+LG1OZEY9ZKD0f0obF2aJlKe+4RTiEksr/wEBCIDRaCXFDvNVdUzrMOTrakj4TL2JYGENe0ifncsN6NjuyKXaSjnXabANAxh/3Km5/iPsB6+NRBX5jYZnnDOszMWJi18u4ChYQQQ8jzTD1Esd4zH8r+a3n/sbdM8H1VQkU20tZlAS2IZyqCWLRLr9q/sopH2VpgPie/9QagiFZ5m/VcOfxGleVR+A7HPerJNxaL7eBMgH+rDU0qTSnKuicaLVJRqXjcKaLyuVULQizVS8ifhqyO16l5z8nk1K7NW2kHSUG9hddB0qLweYwXptMYlVzQ5f80Xh3LeQGss0uQ63TZBZx3A8BXprcVuz7tkKBN9OsYB/E1YT4KzZYmWfz9z/9UzwCShvn7Yn+dsRf6whxXxhMqR2RcuiFprlylFu7lu00/pwDYW5+ThGeExpJrZ8ULd3jZ0L3vyKolKRwGa4SCuZSHi4THm/ZbY2FPfehR/cgnT1EH2Kji+7EY50dVbKIm53Po072T/2bLCfQX6fc8tkWSmtS1aMLIUkJJo8wDHZ5ksUUARXho3ufzR9eR3fqNwL8A2DKUO0//x3U2xUI2nmCt+Aa9FLdzBkOhGBn9fazgfQfxznJY1vXL6g/8/1Pj5AAKNv4l+a2H3KG4HZweSFYE29uBtVs5ndLdWSo532isN6aceQCaAo9muLF4WHy/op3JGIatL7ZcbacWBH6O+MzXmx+GqJnKX8jCEeKWsa4h/rsjkbHm7CdH7dTvwseFXt0VLwKzfCP8OtxkgAAAAA"
                      alt="Object type: FABRICATOR
                      Broad period: NEOLITHIC"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://images.unsplash.com/photo-1488190211105-8b0e65b80b4e?w=500&h=500&fit=crop"
                      alt="person writing in a notebook beside by an iPad, laptop, printed photos, spectacles, and a cup of coffee on a saucer"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://images.unsplash.com/photo-1515260268569-9271009adfdb?w=500&h=500&fit=crop"
                      alt="sunset behind San Francisco city skyline"
                    />
                  </div>
                </a>
                <a href="#">
                  <div className="gallery-item">
                    <img
                      className="gallery-image"
                      src="https://images.unsplash.com/photo-1506045412240-22980140a405?w=500&h=500&fit=crop"
                      alt="people holding umbrellas on a busy street at night lit by street lights and illuminated signs in Tokyo, Japan"
                    />
                  </div> */}
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* <!-- ============================================== Algos ===================================================== --> */}

      <div id="algos">
        <div className="service-content">
          <div className="service-grid text-center">
            <div className="container">
              <div className="row">
                <div className="col-md-12">
                  <div className="main-title text-center wow fadeIn">
                    <h3>Key Components</h3>
                    <div className="underline1"></div>
                    <div className="underline2"></div>
                    <p>
                      Python algorithms provide a detailed set of instructions
                      by which you can process data for a specific purpose. The
                      most well-known are sorting and graph.
                    </p>
                  </div>
                </div>
              </div>
              <div className="row love-row wow fadeIn">
                <div className="col-md-4 col-sm-6">
                  <div className="service-details" data-wow-delay=".1s">
                    <div className="service-head">
                      <img
                        src="https://static.javatpoint.com/tutorial/machine-learning/images/random-forest-algorithm.png"
                        alt="design-development"
                      />
                    </div>
                    <div className="service-bottom">
                      <h3>Random Rainforest Algorithm</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        The random forest algorithm is a machine learning
                        algorithm that combines the results of multiple decision
                        trees to produce a single result. It is a supervised
                        machine learning algorithm that is used for
                        classification and regression problems. The random
                        forest algorithm works by generating a "forest" of
                        decision trees and then combining them to avoid
                        overfitting and produce more accurate predictions.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 col-sm-6">
                  <div className="service-details" data-wow-delay=".1s">
                    <div className="service-head">
                      <img
                        src="https://miro.medium.com/v2/resize:fit:1358/1*RISNojLWzlJsrmip2Qm9NA.jpeg"
                        alt="e-commarce"
                      />
                    </div>
                    <div className="service-bottom">
                      <h3>Greedy Algorithm</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        A greedy algorithm is a simple, intuitive algorithm that
                        finds a solution to problems in the shortest time
                        possible. It makes the optimal choice at each step,
                        without regard for the overall optimization of the
                        solution. Greedy is an algorithmic paradigm that builds
                        up a solution piece by piece, always choosing the next
                        piece that offers the most obvious and immediate
                        benefit. So the problems where choosing locally optimal
                        also leads to global solution are the best fit for
                        Greedy.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 col-sm-6">
                  <div className="service-details" data-wow-delay=".1s">
                    <div className="service-head">
                      <img
                        src="https://editor.analyticsvidhya.com/uploads/59954intro%20to%20CNN.JPG"
                        alt="analytics"
                      />
                    </div>
                    <div className="service-bottom">
                      <h3>CNN</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        A convolutional neural network (CNN) is a type of neural
                        network that learns from data and is used for deep
                        learning. CNNs are useful for finding patterns in images
                        and classifying audio, time-series, and signal data.CNNs
                        use convolutional filters to extract patterns from
                        grid-like data, such as images. They use a series of
                        convolution and pooling layers to extract features from
                        images and videos. These features are then used to
                        classify or detect objects or scenes.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 col-sm-6">
                  <div className="service-details" data-wow-delay=".1s">
                    <div className="service-head">
                      <img
                        src="assets/img/service/mobile-friendly.jpg"
                        alt="mobile-friendly"
                      />
                    </div>
                    <div className="service-bottom">
                      <i
                        className="fa fa-desktop exp-icon"
                        aria-hidden="true"
                      ></i>
                      <h3>Artifact Database</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        Artifact Dataset: Curated dataset comprising images of
                        various cultural artifacts, encompassing diverse
                        historical periods and cultural origins. Images captured
                        from different angles and under various lighting
                        conditions to ensure model robustness.
                      </p>
                    </div>
                  </div>
                </div>
                <div className="col-md-4 col-sm-6">
                  <div className="service-details" data-wow-delay=".1s">
                    <div className="service-head">
                      <img
                        src="assets/img/service/website-audit.jpg"
                        alt="website-audit"
                      />
                    </div>
                    <div className="service-bottom">
                      <h3>Artifact Analysis</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>
                        Classification of artifacts into specific categories
                        (e.g., pottery, sculptures, tools) using the trained CNN
                        model. Extracting key features such as textures,
                        patterns, and shapes for a comprehensive understanding
                        of each artifact.
                      </p>
                    </div>
                  </div>
                </div>
                {/* <div className="col-md-4 col-sm-6">
                  <div className="service-details" data-wow-delay=".1s"> */}
                {/* <div className="service-head">
                      <img
                        src="assets/img/service/content-management.jpg"
                        alt="content-management"
                      />
                    </div> */}
                {/* <div className="service-bottom">
                      <h3>Demo</h3>
                      <div className="underline1"></div>
                      <div className="underline2"></div>
                      <p>Demo</p>
                    </div> */}
                {/* </div>
                </div> */}
              </div>
            </div>
          </div>
          
        </div>
      </div>

      

      {/* <!-- ================================ Our Team ========================== --> */}

      <div className="row main-row wow fadeIn">
        <div className="col-md-12">
          <div className="main-title text-center">
            <h3>Our Team</h3>
            <div className="underline1"></div>
            <div className="underline2"></div>
            <p>Our project team!!!</p>
          </div>
        </div>
      </div>
      <div className="row love-row">
        <div className="col-md-6 col-sm-12">
          <div className="exp-details" data-wow-delay=".2s">
            <div className="exp-hover"></div>
            <div className="exp-main">
              <i className="fa fa-building exp-icon" aria-hidden="true"></i>
              {/*<h3>
                           <a
                            href="https://patelgtech.com/"
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{ color: "#4d4d4d" }}
                          >
                            Patel G Tech LLP
                          </a>
                        </h3>
                        <h4>Repub Member</h4> */}
              <h2>Rupashi Goel </h2>
              <h2>Soven </h2>
              <h2>Dhruv </h2>
              <h2>Pranshu </h2>
              <div className="underline1"></div>
              <div className="underline2"></div>
              {/* <p>
                          I did an internship at PATEL G TECH LLP as a
                          Republication Team Member
                        </p> */}
            </div>
          </div>
        </div>
        {/* <div className="col-md-6 col-sm-12">
                    <div className="exp-details" data-wow-delay=".3s">
                      <div className="exp-hover"></div>
                      <div className="exp-main">
                        <i
                          className="fa fa-building exp-icon"
                          aria-hidden="true"
                        ></i>
                        <h3>
                          <a
                            href="https://uaguria.com/"
                            target="_blank"
                            rel="noopener noreferrer"
                            style={{ color: "#4d4d4d" }}
                          >
                            Uaguria Software
                          </a>
                        </h3>
                        <h4>Web Developer</h4>
                        <h2>2020-2022</h2>
                        <div className="underline1"></div>
                        <div className="underline2"></div>
                        <p>
                          At Uaguria Software, I was working as a Web Developer
                          &amp; IT Consultant Person
                        </p>
                      </div>
                    </div>
                  </div>
                  <div className="col-md-4 col-sm-4">
                    <div className="exp-details" data-wow-delay=".4s">
                      <div className="exp-hover"></div>
                      <div className="exp-main">
                        <i
                          className="fa fa-cogs exp-icon"
                          aria-hidden="true"
                        ></i>
                        <h3>Supreme Company</h3>
                        <h4>Designer &amp; Developer</h4>
                        <h2>2013-2016</h2>
                        <div className="underline1"></div>
                        <div className="underline2"></div>
                        <p>Lorem Ipsum is simply dummy text of the printing.</p>
                      </div>
                    </div>
                  </div> */}

        {/* <!-- ================================ CONTACT ========================== --> */}

        <div id="contact">
          <div className="contact-content">
            <div className="text-grid">
              <div className="text-grid-main">
                <div className="container">
                  <div className="row">
                    <div className="col-md-12 col-sm-12">
                      <div className="main-title text-center wow fadeIn">
                        <h3>Contact Us</h3>
                        <div className="underline1"></div>
                        <div className="underline2"></div>
                        <p>If you like our product feel free to contact</p>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="contact-grid">
              <div className="contact-form-details wow fadeIn">
                <div className="container">
                  {/* <div className="row contact-row">
                    <div className="col-md-8 col-md-offset-2 col-sm-12 col-sm-offset-1 contact-col">
                      <h3>Write Your Message Here</h3>
                      <div className="contact-form">
                        <form
                          action="https://herokuapp.us6.list-manage.com/subscribe/post?u=870e1b447d1f93893227a9c52&amp;id=85d6c939a5"
                          method="post"
                          id="mc-embedded-subscribe-form contactForm"
                          name="mc-embedded-subscribe-form"
                          className="contact-form shake validate"
                          target="_blank" 
                          data-toggle="validator"
                          novalidate
                        >
                          <div className="form-group">
                            <div className="controls">
                              <input
                                type="text"
                                name="FLNAME"
                                id="mce-FLNAME"
                                className="required form-control"
                                placeholder="Your Name"
                                required
                                data-error="Please enter your name"
                              />
                              <div className="help-block with-errors"></div>
                            </div>
                          </div>
                          <div className="form-group">
                            <div className="controls">
                              <input
                                type="email"
                                className="email required form-control"
                                name="EMAIL"
                                id="mce-EMAIL"
                                placeholder="Your Email"
                                required
                                data-error="Please enter your email"
                              />
                              <div className="help-block with-errors"></div>
                            </div>
                          </div>
                          <div className="form-group">
                            <div className="controls">
                              <input
                                type="phone"
                                name="PHONE"
                                className="phone form-control"
                                id="phone mce-PHONE"
                                placeholder="Your Phone"
                                required
                                data-error="Please enter your phone"
                              />
                              <div className="help-block with-errors"></div>
                            </div>
                          </div>
                          <div className="form-group">
                            <div className="controls">
                              <textarea
                                id="message mce-MESSAGE"
                                rows="7"
                                placeholder="Your Massage"
                                name="MESSAGE"
                                className="required form-control"
                                required
                                data-error="Please enter your message"
                              ></textarea>
                              <div className="help-block with-errors"></div>
                            </div>
                          </div>
                          <div id="mce-responses" class="clear">
                            <div
                              class="response"
                              id="mce-error-response"
                              style={{ display: "none" }}
                            ></div>
                            <div
                              class="response"
                              id="mce-success-response"
                              style={{ display: "none" }}
                            ></div>
                          </div>
                          <div
                            style={{ position: "absolute", left: "-5000px" }}
                            aria-hidden="true"
                          >
                            <input
                              type="text"
                              name="b_870e1b447d1f93893227a9c52_85d6c939a5"
                              tabindex="-1"
                              value=""
                            />
                          </div>
                          <button
                            type="submit"
                            value="Subscribe"
                            name="subscribe"
                            id="submit mc-embedded-subscribe"
                            className="btn btn-success"
                          >
                            Send Message
                          </button>
                          <div
                            id="msgSubmit"
                            className="h3 text-center hidden"
                          ></div>
                          <div className="clearfix"></div>
                        </form>
                      </div>
                    </div>
                  </div> */}
                  <div className="row contact-info-row text-center wow fadeIn">
                    <div className="col-md-3 col-sm-6 contact-colamn">
                      <div className="contact-col-info" data-wow-delay=".2s">
                        <i
                          className="fa fa-map-marker contact-icon"
                          aria-hidden="true"
                        ></i>
                        <h3>Address</h3>
                        <p>
                          PSP-4, Dr. KN Katju Marg, Sector17, Rohini, New Delhi,
                          Delhi 110089
                        </p>
                      </div>
                    </div>
                    <div className="col-md-3 col-sm-6 contact-colamn">
                      <div className="contact-col-info" data-wow-delay=".4s">
                        <i
                          className="fa fa-envelope contact-icon"
                          aria-hidden="true"
                        ></i>
                        <h3>Email</h3>
                        <a
                          href="mailto:contact.sanajitjana@gmail.com"
                          style={{
                            color: "black",
                            textDecoration: "none",
                            fontSize: "17px",
                          }}
                        >
                          pranshukaushik1@gmail.com
                        </a>
                      </div>
                    </div>
                    {/* <div className="col-md-3 col-sm-6 contact-colamn">
                      <div className="contact-col-info" data-wow-delay=".6s">
                        <i
                          className="fa fa-mobile contact-icon"
                          aria-hidden="true"
                        ></i>
                        <h3>Phone</h3>
                        <a
                          href="tel:8372876775"
                          style={{
                            color: "black",
                            textDecoration: "none",
                            fontSize: "17px",
                          }}
                        >
                          +91 8372876775
                        </a>
                      </div>
                    </div> */}
                    {/* <div className="col-md-3 col-sm-6 contact-colamn">
                      <div className="contact-col-info" data-wow-delay=".6s">
                        <i
                          className="fa fa-television contact-icon"
                          aria-hidden="true"
                        ></i>
                        <h3>Portfolio</h3>
                        <p>https://sanajitjana.github.io/</p>
                      </div>
                    </div> */}
                  </div>
                </div>
                <div class="container-fluid map-col">
                  <div class="col-md-12 col-sm-12 map-col">
                    <div class="google-maps">
                      <div class="map-wrap">
                        {/* <iframe
                          title="google-maps"
                          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3498.427581241061!2d77.10975907550464!3d28.736648175608078!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d013045aab491%3A0xb6a504893549c54f!2sBhagwan%20Parshuram%20Institute%20of%20Technology!5e0!3m2!1sen!2sin!4v1708469553106!5m2!1sen!2sin"
                          width="800"
                          height="600"
                          style="border:0;"
                          allowfullscreen=""
                          loading="lazy"
                          referrerpolicy="no-referrer-when-downgrade"
                          width ="100%"
                          height="450"
                          style={{ border: "0" }}
                          allowfullscreen=""
                          loading="lazy"
                          referrerpolicy="no-referrer-when-downgrade"
                        ></iframe> */}

                        <iframe
                          title="google-maps"
                          src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3498.427581241061!2d77.10975907550464!3d28.736648175608078!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x390d013045aab491%3A0xb6a504893549c54f!2sBhagwan%20Parshuram%20Institute%20of%20Technology!5e0!3m2!1sen!2sin!4v1708469553106!5m2!1sen!2sin"
                          width="100%"
                          height="450"
                          style={{ border: "0" }}
                          allowfullscreen=""
                          loading="lazy"
                          referrerpolicy="no-referrer-when-downgrade"
                        ></iframe>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
